title: Danny Chadburn
description: Content Creator | Gardener
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  
  plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes
